Created UserProfile Model
sanscript-tech/medical-emergency-flutter-node pull request #66
Opened 2020-10-31 21:51 UTC by Shubham-1105

closes #44

2020-11-02 18:43 UTC, mbcse commented
Hey @Shubham-1105 , fix the conflict and also please refer hospital data to hospitals model. Also it seems some things are missing in the model, please check the UI page and update accordingly

2020-11-03 07:55 UTC, Shubham-1105 commented
There will be no hospital model,so i added it as an array in the user Profile.Also can suggest the more fields that are required.

2020-11-03 10:52 UTC, Codess08 commented
![11-Profile Page (1)](https://user-images.githubusercontent.com/44175278/97976451-b884ce80-1df0-11eb-99f0-d04bc7e1f7f5.PNG)

2020-11-03 10:59 UTC, Codess08 commented
And also we will make a hospital model, and the hospital fields you have added looks fine, you can simply copy that into the issue "create hospital model".

And, for doctor either we can add some extra fields to user model and add a property of isDoctor which will be true or false, or we can also create a doctor model both of them will be okay.

2020-11-03 11:36 UTC, Shubham-1105 commented
fixes #44 and #74

2020-11-03 13:25 UTC, Codess08 requested changes

2020-11-03 13:25 UTC, Codess08 commented on server/src/models/userProfile.js
> +    isDoctor: {
I have created a separate model for Doctor, so you can remove the isDoctor field.

2020-11-03 13:25 UTC, Codess08 commented on server/src/models/hospital.js
> +const mongoose = require("mongoose");
Since this is a separate issue please create a different PR for it.
I can award points on the basis of merged PR.

2020-11-03 13:25 UTC, Codess08 commented on server/src/models/hospital.js
> +    availableBeds: {
Add default : 0
for numberOfDoctors, availableBeds, ratings

2020-11-03 13:25 UTC, Codess08 commented on server/src/models/userProfile.js
> +module.exports = mongoose.model("userProfile", userProfileSchema);
Rest of the code is absolutely fine.

2020-11-03 17:46 UTC, closed without merging